name: 'Sync: Upstream nvm-sh/nvm'

on:
  schedule:
    # Run every Monday at 03:00 UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:
    inputs:
      force:
        description: 'Force sync even if no changes'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-upstream:
    name: 'Sync with nvm-sh/nvm'
    runs-on: ubuntu-latest
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            github.com:443
            api.github.com:443
      
      - name: Checkout ERIFY(TM) nvm
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "ERIFY(TM) Bot"
          git config user.email "bot@erify.world"
      
      - name: Detect default branch
        id: default-branch
        run: |
          # Get the default branch name
          DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          if [ -z "$DEFAULT_BRANCH" ]; then
            # Fallback: try to detect from remote
            DEFAULT_BRANCH=$(git ls-remote --symref origin HEAD | grep '^ref:' | sed 's@^ref: refs/heads/@@')
          fi
          if [ -z "$DEFAULT_BRANCH" ]; then
            # Final fallback
            DEFAULT_BRANCH="master"
          fi
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT
          echo "TARGET: Detected default branch: $DEFAULT_BRANCH"
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/nvm-sh/nvm.git || true
          git remote -v
      
      - name: Fetch upstream changes
        run: |
          echo "SYNC: Fetching upstream changes..."
          git fetch upstream
          git fetch origin
      
      - name: Check for upstream changes
        id: check-changes
        run: |
          DEFAULT_BRANCH="${{ steps.default-branch.outputs.default_branch }}"
          
          # Get the latest commit from upstream master
          UPSTREAM_COMMIT=$(git rev-parse upstream/master)
          
          # Get the latest commit from our default branch  
          LOCAL_COMMIT=$(git rev-parse origin/$DEFAULT_BRANCH)
          
          echo "upstream_commit=$UPSTREAM_COMMIT" >> $GITHUB_OUTPUT
          echo "local_commit=$LOCAL_COMMIT" >> $GITHUB_OUTPUT
          
          if [ "$UPSTREAM_COMMIT" = "$LOCAL_COMMIT" ]; then
            echo "changes_available=false" >> $GITHUB_OUTPUT
            echo "INFO: No upstream changes detected"
          else
            echo "changes_available=true" >> $GITHUB_OUTPUT
            echo "INFO: Upstream changes detected!"
            echo "  Local:    $LOCAL_COMMIT"
            echo "  Upstream: $UPSTREAM_COMMIT"
          fi
      
      - name: Create sync branch
        if: steps.check-changes.outputs.changes_available == 'true' || github.event.inputs.force == 'true'
        id: sync-branch
        run: |
          DEFAULT_BRANCH="${{ steps.default-branch.outputs.default_branch }}"
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          BRANCH_NAME="sync/upstream-$TIMESTAMP"
          
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "BRANCH: Creating sync branch: $BRANCH_NAME"
          
          # Checkout default branch and create new sync branch
          git checkout $DEFAULT_BRANCH
          git checkout -b $BRANCH_NAME
      
      - name: Merge upstream changes
        if: steps.check-changes.outputs.changes_available == 'true' || github.event.inputs.force == 'true'
        id: merge
        run: |
          DEFAULT_BRANCH="${{ steps.default-branch.outputs.default_branch }}"
          
          echo "MERGE: Attempting to merge upstream changes..."
          
          # Try to merge upstream/master
          if git merge upstream/master --no-edit -m "SYNC: Sync with upstream nvm-sh/nvm
          
          Merging latest changes from upstream nvm-sh/nvm repository.
          
          - Upstream commit: ${{ steps.check-changes.outputs.upstream_commit }}
          - Previous commit: ${{ steps.check-changes.outputs.local_commit }}
          
          This automated sync ensures ERIFY(TM) nvm stays up-to-date with the latest
          features, bug fixes, and security improvements from the upstream project.
          
          Source: https://github.com/nvm-sh/nvm"; then
            echo "merge_success=true" >> $GITHUB_OUTPUT
            echo "SUCCESS: Merge successful!"
            
            # Show summary of changes
            echo "SUMMARY: Changes summary:"
            git log --oneline ${{ steps.check-changes.outputs.local_commit }}..${{ steps.check-changes.outputs.upstream_commit }}
          else
            echo "merge_success=false" >> $GITHUB_OUTPUT
            echo "ERROR: Merge failed - conflicts detected"
            
            # Show conflicted files
            echo "WARNING: Conflicted files:"
            git status --porcelain | grep "^UU\|^AA\|^DD" || echo "No conflicted files found"
            
            # Reset the merge
            git merge --abort
          fi
      
      - name: Push sync branch
        if: (steps.check-changes.outputs.changes_available == 'true' || github.event.inputs.force == 'true') && steps.merge.outputs.merge_success == 'true'
        run: |
          BRANCH_NAME="${{ steps.sync-branch.outputs.branch_name }}"
          echo "PUSH: Pushing sync branch: $BRANCH_NAME"
          git push origin $BRANCH_NAME
      
      - name: Create Pull Request
        if: (steps.check-changes.outputs.changes_available == 'true' || github.event.inputs.force == 'true') && steps.merge.outputs.merge_success == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEFAULT_BRANCH="${{ steps.default-branch.outputs.default_branch }}"
          BRANCH_NAME="${{ steps.sync-branch.outputs.branch_name }}"
          
          # Get commit count and first/last commit info for PR description
          COMMIT_COUNT=$(git rev-list --count ${{ steps.check-changes.outputs.local_commit }}..${{ steps.check-changes.outputs.upstream_commit }})
          FIRST_COMMIT=$(git log --format="%h %s" ${{ steps.check-changes.outputs.local_commit }}..${{ steps.check-changes.outputs.upstream_commit }} | tail -1)
          LAST_COMMIT=$(git log --format="%h %s" ${{ steps.check-changes.outputs.upstream_commit }} -1)
          
          # Create PR using gh CLI with simple description
          echo "CREATE: Creating Pull Request..."
          TITLE="SYNC: Sync upstream nvm-sh/nvm changes ($COMMIT_COUNT commits)"
          BODY="Automated upstream sync. Commits: $COMMIT_COUNT. Upstream: ${{ steps.check-changes.outputs.upstream_commit }}. Previous: ${{ steps.check-changes.outputs.local_commit }}. This sync ensures ERIFY(TM) nvm stays up-to-date with upstream changes."
          
          gh pr create \
            --title "$TITLE" \
            --body "$BODY" \
            --base "$DEFAULT_BRANCH" \
            --head "$BRANCH_NAME" \
            --label "upstream-sync" \
            --label "automated"
          
          echo "SUCCESS: Pull Request created successfully!"
      
      - name: Handle merge conflicts
        if: (steps.check-changes.outputs.changes_available == 'true' || github.event.inputs.force == 'true') && steps.merge.outputs.merge_success == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "WARNING: Merge conflicts detected - creating issue for manual resolution"
          
          # Create issue with simple description
          ISSUE_TITLE="ALERT: Manual upstream sync required - merge conflicts detected"
          ISSUE_BODY="Upstream sync conflict detected. Upstream: ${{ steps.check-changes.outputs.upstream_commit }}. Local: ${{ steps.check-changes.outputs.local_commit }}. Manual resolution required. Please create a sync branch and merge upstream/master manually."
          
          gh issue create \
            --title "$ISSUE_TITLE" \
            --body "$ISSUE_BODY" \
            --label "upstream-sync" \
            --label "manual-resolution-required" \
            --label "conflicts"
      
      - name: Summary
        if: always()
        run: |
          echo "## Upstream Sync Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.check-changes.outputs.changes_available }}" == "true" ]; then
            if [ "${{ steps.merge.outputs.merge_success }}" == "true" ]; then
              echo "SUCCESS: **Success**: Upstream changes synced and PR created" >> $GITHUB_STEP_SUMMARY
            else
              echo "WARNING: **Conflicts**: Manual resolution required - issue created" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "INFO: **No Changes**: ERIFY(TM) nvm is up-to-date with upstream" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Default Branch**: ${{ steps.default-branch.outputs.default_branch }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Upstream Commit**: ${{ steps.check-changes.outputs.upstream_commit }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Local Commit**: ${{ steps.check-changes.outputs.local_commit }}" >> $GITHUB_STEP_SUMMARY